### ISSUE TITLE
Is the StorageAPI broken?

### ISSUE THREAD

**Issue by tianrenli92** [Elinea/dota2-StorageAPI#1]
My mod Dota Global Skillshots is using your storageAPI and mulfunctions today. Would you please solve the problem? Thanks!

dota2.tools/api/v1/storage?api_key=fc80985d01e14165c9ca9d03848eaecd58d3ede3&steam_id=161697269

**Comment by mtricht** [comment]
Should be back up now, sorry for the inconvenience.

**Comment by tianrenli92** [comment]
Recovered. Ty.

**Comment by Ambassador601** [comment]
Hi there. Is something wrong with it ATM?

**Comment by mtricht** [comment]
@Ambassador601 Can you check if it's working again?

**Comment by Ambassador601** [comment]
Everything's fine now! Thanks!
I'm scared of the thought about building my own reciever, as I know nothing about it.
Thank you very much.

**Comment by Ambassador601** [comment]
Same issue, again.
EDIT: and back again. Thanks!

**Comment by Ambassador601** [comment]
And broken again.
What's happening?

**Comment by han0jong** [comment]
Hello, I am Korean and I am using a translation question by google.
I have made a custom map of dota2 for about 5 months.
Implementing a level storage system is difficult and has a lot of delays.
A month later, the search found the StorageAPI.
But still can't solve some problem.

1)I can't make api id by  "http://dota2.tools/api/v1/storage/". Is there any guide or something?
1-2)I found some guide about steam web api (https://steamwebapi.azurewebsites.net/)
so there are some data when I touch "http://api.steampowered.com/ISteamWebAPIUtil/GetSupportedAPIList/v1/?key=2EAA9276CA8750DFA2EADAD757A07544&steamid=76561198009353172"
Is it any relationship, or chance?
3)I little understand the example. especially, "function( resultTable, successBool )" in example.
need to put another thing? or literally resultTalbe, and successBool.
4)I also failed when I test print("working") in any storage, but DeepPrintTable show null.
Is it nature when I try to "print in storage.lua" fail?

Koreans are not interested in making dota2 custom maps and have no data. I am very depressed. If anyone can help me, please help me. If possible, I would like to contact you by email. han9jong@naver.com. It was made in 2015, please reply if you see. Thank you.
