### ISSUE TITLE
Security Issues

### ISSUE THREAD

**Issue by Ambassador601** [Elinea/dota2-StorageAPI#2]
Hi there and thank you for making the lib and hosting the storage for us.
If you are still around, i would have liked to know if your storage uses some kinds of checks whether the put/get requests were sent from a legitimate addon, or if it's just a scumbag trying to disrupt the data? How safe is it?
And if you have any advices on how to stop cheated data (gold/levels etc) from being stored i would gladly listen.
Big thanks in advance!

**Comment by Ambassador601** [comment]
Okay, i tested it myself.
For now it seems like there isn't any protection of the data.
Should I host my own storage if this is crucial for my game or are you planning on implementing some security checks?

**Comment by Elinea** [comment]
Hey Ambassador601,

I'm afraid the API that Valve provides us for modding doesn't allow for sessions or security checks. At least not when I made the StorageAPI.

You could host your own storage to decrease the chances of someone messing with your data, but even then, if someone wants to do harm and decompiles your mod to get your API key, they can also just check for the new server adress. You can also fork the project and try to implement your own solution.

I hope this answers your question.

**Comment by Ambassador601** [comment]
Thanks for the reply!
I guess i'm off to find a solution on my own, if it exists.
